### PR TITLE
158423392 dashboard

### PR DESCRIPTION
**Pull request by xcixor**
#### Purpose of the PR
* Creates the driver's workspace
#### Tasks to be complete
* Create the driver's dashboard
* Create ride details collection form
#### Manual testing
* Navigate to the repo's main page via  [this link](https://github.com/xcixor/my-ride)
* Under the repo's name copy the clone's url
* Open a terminal and navigate to where you want the repo to be downloaded
* Type git clone 'the url you copied above' and press enter to download
* Checkout to the branch 158423392-dashboard
* Navigate to the UI folder
* Open the index file with your favorite browser
* Click on Signup in the navbar
* Enter some dummy data and press enter
* To preview on mobile in chrome inspect the page and the browser's inspection tool will provide 
   previews for various screens
#### Relevant pivotal tracker stories 
[A driver should be able to create a ride](https://www.pivotaltracker.com/n/projects/2179559)
####Screenshots
driverdashdesk
driverdashmobile
ridedesk
ridemobile

### CODE REVIEW

**Comment by evamaina** [comment]
look nice

**Comment by ghost** [comment]
What is origing ?
Simply it

**Comment by ghost** [comment]
code is okay

**Comment by artorious** [comment]
User input is well captured

**Pull request closed without merging**
